import * as _ from 'lodash'; 
import './css/styles.css';
import './assets/BoxRender.mp4';
import './heroSectionVideoScrubbing';
import './visibleHandler';
import './assets/stock.png';
import './assets/DesignDays_Logo_turkis.png';
import './textScrolling';
import './assets/SaxophoneGuy.jpg';
import './assets/Bühne.jpg';
